name: Atualizar Hinos do Domingo

on:
  push:
    paths:
      - "repertorios/*.json"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Gerar página do domingo
        run: node gerar-domingo.js

      - name: Commit das alterações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add repertorio-atual.json
          git add hinos-do-domingo.html

          if git diff --cached --quiet; then
            echo "Nenhuma alteração encontrada."
          else
            git commit -m "Atualiza hinos do domingo"
            git push
          fi
